style: bitbucket
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://bitbucket.org/olivje_group/olivje.crm.pl
options:
  commits:
    filters:
      Type:
        - feature
        - fix
        - hotfix
        - test
        - chore
  commit_groups:
    title_maps:
      feature: Features
      fix: Bug Fixes
      hotfix: Hotfix
      test: Tests writing
      chore: Minor fixes
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE